# Generated by Django 4.0 on 2022-11-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='housesale',
            fields=[
                ('housesale_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('housesale_title', models.CharField(max_length=30)),
                ('housesale_description', models.CharField(max_length=250)),
                ('housesale_image', models.ImageField(blank=True, null=True, upload_to='house')),
            ],
        ),
    ]
