# Generated by Django 4.0 on 2022-11-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('User_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('User_Name', models.CharField(max_length=20)),
                ('User_LastName', models.CharField(max_length=20)),
                ('User_Mail', models.EmailField(max_length=254)),
                ('User_Date', models.DateField()),
            ],
        ),
    ]
