# Generated by Django 4.0 on 2022-11-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSale', '0002_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('Price_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Price_Number', models.CharField(max_length=20)),
                ('Price_Special', models.CharField(max_length=20)),
                ('Price_Money', models.CharField(max_length=50)),
                ('Price_Line1', models.CharField(max_length=50)),
                ('Price_Line2', models.CharField(max_length=50)),
                ('Price_Line3', models.CharField(max_length=50)),
                ('Price_Line4', models.CharField(max_length=50)),
                ('Price_Line5', models.CharField(max_length=50)),
                ('Price_Line6', models.CharField(max_length=50)),
                ('Price_URL', models.URLField()),
            ],
        ),
    ]
